# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from fastapi import FastAPI
from pydantic import BaseModel
from typing import List
from datetime import datetime, timedelta

app = FastAPI(title="Failures API")

# مدل داده‌ها
class FailureItem(BaseModel):
    label: str
    type: str
    color: str
    timestamp: datetime  # اضافه کردن فیلد زمان

class FailuresResponse(BaseModel):
    items: List[FailureItem]

# Endpoint
@app.get("/api/failures", response_model=FailuresResponse)
def get_failures():
    now = datetime.utcnow()  # زمان کنونی به UTC
    return {
        "items": [
            {"label": "Flow Instability", "type": "AI", "color": "#ff3b30", "timestamp": now - timedelta(minutes=30)},
            {"label": "Pressure Anomaly", "type": "AI", "color": "#ff3b30", "timestamp": now - timedelta(hours=1)},
            {"label": "Chemical Composition", "type": "AI", "color": "#ffcc00", "timestamp": now - timedelta(minutes=10)},
            {"label": "Temperature Anomaly", "type": "AI", "color": "#34c759", "timestamp": now - timedelta(minutes=45)},
            {"label": "Fluid Level Anomaly", "type": "AI", "color": "#34c759", "timestamp": now - timedelta(hours=2)},
            {"label": "Viscosity Anomaly", "type": "AI", "color": "#34c759", "timestamp": now - timedelta(minutes=5)}
        ]
    }